=== trabz777/NoSQL-Databases-Implementation/zip file/schema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$id": "http://example.com/product.schema.json",
    "title": "Grocerry Store Food",
    "description": "Some fresh products available in the store",
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "title": {
                "description": "Name of the product",
                "type": "string"
            },
            "type": {
                "description": "Type of product.Is it vegetable, fruit or something else?",
                "type": "string"
            },
            "description": {
                "description": "Description of product and its ingredients",
                "type": "string"
            },
            "filename": {
                "description": "Name of the product's photo file",
                "type": "string"
            },
            "height": {
                "type": "number",
                "minimum": 0
            },
            "width": {
                "type": "number",
                "minimum": 0
            },
            "price": {
                "type": "number",
                "exclusiveMinimum": 0
            },
            "rating": {
                "type": "number",
                "maximum": 10,
                "minimum": 0
            },
            "ingredients": {
                "description": "Different Ingredients which makes the product",
                "type": "array",
                "items": {
                    "type": "string"
                },
                "minItems": 1,
                "uniqueItems": true
            },
            "relatedProducts": {
                "description": "An object array which stores the related products",
                "type": "array",
                "items": {
                    "type": "object",
                    "properties": {
                        "title": {
                            "description": "Name of the product",
                            "type": "string"
                        },
                        "type": {
                            "description": "Type of product.Is it vegetable, fruit or something else?",
                            "type": "string"
                        },
                        "description": {
                            "description": "Description of product and its ingredients",
                            "type": "string"
                        },
                        "filename": {
                            "description": "Name of the product's photo file",
                            "type": "string"
                        },
                        "height": {
                            "type": "number",
                            "minimum": 0
                        },
                        "width": {
                            "type": "number",
                            "minimum": 0
                        },
                        "price": {
                            "type": "number",
                            "exclusiveMinimum": 0
                        },
                        "rating": {
                            "type": "number",
                            "maximum": 10,
                            "minimum": 0
                        }
                    },
                    "required": [
                        "title",
                        "type",
                        "description",
                        "filename",
                        "height",
                        "width",
                        "price",
                        "rating"
                    ]
                },
                "uniqueItems": true
            }
        }
    }
}

=== trabz777/NoSQL-Databases-Implementation/zip file/dataset.json
[
    {
        "title": "Brown eggs",
        "type": "dairy",
        "description": "Raw organic brown eggs in a basket",
        "filename": "0.jpg",
        "height": 600,
        "width": 400,
        "price": 28.1,
        "rating": 4,
        "ingredients": [
            "Butter",
            "Heavy cream",
            "Eggs",
            "Parmesan",
            "Bacon",
            "Parsley",
            "Celery",
            "Carrots",
            "Lemons",
            "Limes",
            "Orange",
            "juice"
        ],
        "relatedProducts": [
            {
                "title": "Strawberry and mint",
                "type": "fruit",
                "description": "Homemade muesli with strawberry and mint",
                "filename": "26.jpg",
                "height": 450,
                "width": 299,
                "price": 26.21,
                "rating": 4
            },
            {
                "title": "Ricotta",
                "type": "dairy",
                "description": "Ricotta with berry and mint",
                "filename": "27.jpg",
                "height": 600,
                "width": 398,
                "price": 27.81,
                "rating": 5
            },
            {
                "title": "Cuban sandwiche",
                "type": "bakery",
                "description": "Homemade traditional cuban sandwiches with ham pork and cheese",
                "filename": "28.jpg",
                "height": 450,
                "width": 300,
                "price": 18.5,
                "rating": 4
            }
        ]
    },
    {
        "title": "Sweet fresh stawberry",
        "type": "fruit",
        "description": "Sweet fresh stawberry on the wooden table",
        "filename": "1.jpg",
        "height": 450,
        "width": 299,
        "price": 29.45,
        "rating": 4,
        "ingredients": [
            "Butter",
            "Heavy cream",
            "Eggs",
            "Parmesan",
            "Bacon",
            "Parsley",
            "Celery",
            "Carrots",
            "Lemons",
            "Limes",
            "Orange",
            "juice"
        ],
        "relatedProducts": [
            {
                "title": "Strawberry and mint",
                "type": "fruit",
                "description": "Homemade muesli with strawberry and mint",
                "filename": "26.jpg",
                "height": 450,
                "width": 299,
                "price": 26.21,
                "rating": 4
            },
            {
                "title": "Ricotta",
                "type": "dairy",
                "description": "Ricotta with berry and mint",
                "filename": "27.jpg",
                "height": 600,
                "width": 398,
                "price": 27.81,
                "rating": 5
            },
            {
                "title": "Cuban sandwiche",
                "type": "bakery",
                "description": "Homemade traditional cuban sandwiches with ham pork and cheese",
                "filename": "28.jpg",
                "height": 450,
                "width": 300,
                "price": 18.5,
                "rating": 4
            }
        ]
    },
    {
        "title": "Asparagus",
        "type": "vegetable",
        "description": "Asparagus with ham on the wooden table",
        "filename": "2.jpg",
        "height": 450,
        "width": 299,
        "price": 18.95,
        "rating": 3
    },
    {
        "title": "Green smoothie",
        "type": "dairy",
        "description": "Glass of green smoothie with quail egg's yolk, served with cocktail tube, green apple and baby spinach leaves over tin surface.",
        "filename": "3.jpg",
        "height": 600,
        "width": 399,
        "price": 17.68,
        "rating": 4
    },
    {
        "title": "Raw legums",
        "type": "vegetable",
        "description": "Raw legums on the wooden table",
        "filename": "4.jpg",
        "height": 450,
        "width": 299,
        "price": 17.11,
        "rating": 2,
        "ingredients": [
            "Butter",
            "Heavy cream",
            "Eggs",
            "Parmesan",
            "Bacon",
            "Parsley",
            "Celery",
            "Carrots",
            "Lemons",
            "Limes",
            "Orange",
            "juice"
        ]
    },
    {
        "title": "Baking cake",
        "type": "dairy",
        "description": "Baking cake in rural kitchen - dough  recipe ingredients (eggs, flour, sugar) on vintage wooden table from above.",
        "filename": "5.jpg",
        "height": 450,
        "width": 675,
        "price": 11.14,
        "rating": 4,
        "relatedProducts": [
            {
                "title": "Strawberry and mint",
                "type": "fruit",
                "description": "Homemade muesli with strawberry and mint",
                "filename": "26.jpg",
                "height": 450,
                "width": 299,
                "price": 26.21,
                "rating": 4
            },
            {
                "title": "Ricotta",
                "type": "dairy",
                "description": "Ricotta with berry and mint",
                "filename": "27.jpg",
                "height": 600,
                "width": 398,
                "price": 27.81,
                "rating": 5
            },
            {
                "title": "Cuban sandwiche",
                "type": "bakery",
                "description": "Homemade traditional cuban sandwiches with ham pork and cheese",
                "filename": "28.jpg",
                "height": 450,
                "width": 300,
                "price": 18.5,
                "rating": 4
            }
        ]
    },
    {
        "title": "Pesto with basil",
        "type": "vegetable",
        "description": "Italian traditional pesto with basil, chesse and oil",
        "filename": "6.jpg",
        "height": 450,
        "width": 299,
        "price": 18.19,
        "rating": 2,
        "ingredients": [
            "Butter",
            "Heavy cream",
            "Eggs",
            "Parmesan",
            "Bacon",
            "Parsley",
            "Celery",
            "Carrots",
            "Lemons",
            "Limes",
            "Orange",
            "juice"
        ]
    },
    {
        "title": "Hazelnut in black ceramic bowl",
        "type": "vegetable",
        "description": "Hazelnut in black ceramic bowl on old wooden background. forest wealth. rustic style. selective focus",
        "filename": "7.jpg",
        "height": 450,
        "width": 301,
        "price": 27.35,
        "rating": 0
    },
    {
        "title": "Fresh stawberry",
        "type": "fruit",
        "description": "Sweet fresh stawberry on the wooden table",
        "filename": "8.jpg",
        "height": 600,
        "width": 399,
        "price": 28.59,
        "rating": 4,
        "ingredients": [
            "Butter",
            "Heavy cream",
            "Eggs",
            "Parmesan",
            "Bacon",
            "Parsley",
            "Celery",
            "Carrots",
            "Lemons",
            "Limes",
            "Orange",
            "juice"
        ]
    },
    {
        "title": "Lemon and salt",
        "type": "fruit",
        "description": "Rosemary, lemon and salt on the table",
        "filename": "9.jpg",
        "height": 450,
        "width": 299,
        "price": 15.79,
        "rating": 5,
        "relatedProducts": [
            {
                "title": "Strawberry and mint",
                "type": "fruit",
                "description": "Homemade muesli with strawberry and mint",
                "filename": "26.jpg",
                "height": 450,
                "width": 299,
                "price": 26.21,
                "rating": 4
            },
            {
                "title": "Ricotta",
                "type": "dairy",
                "description": "Ricotta with berry and mint",
                "filename": "27.jpg",
                "height": 600,
                "width": 398,
                "price": 27.81,
                "rating": 5
            },
            {
                "title": "Cuban sandwiche",
                "type": "bakery",
                "description": "Homemade traditional cuban sandwiches with ham pork and cheese",
                "filename": "28.jpg",
                "height": 450,
                "width": 300,
                "price": 18.5,
                "rating": 4
            }
        ]
    },
    {
        "title": "Homemade bread",
        "type": "bakery",
        "description": "Homemade bread",
        "filename": "10.jpg",
        "height": 450,
        "width": 301,
        "price": 17.48,
        "rating": 3
    },
    {
        "title": "Legums",
        "type": "vegetable",
        "description": "Cooked legums on the wooden table",
        "filename": "11.jpg",
        "height": 600,
        "width": 399,
        "price": 14.77,
        "rating": 0,
        "relatedProducts": [
            {
                "title": "Strawberry and mint",
                "type": "fruit",
                "description": "Homemade muesli with strawberry and mint",
                "filename": "26.jpg",
                "height": 450,
                "width": 299,
                "price": 26.21,
                "rating": 4
            },
            {
                "title": "Ricotta",
                "type": "dairy",
                "description": "Ricotta with berry and mint",
                "filename": "27.jpg",
                "height": 600,
